Profile Collected Collections UI
holaplex/dao-marketplace pull request #39
Opened 2022-08-19 11:13 UTC by alchemistgo87

Addresses: #15

2022-08-19 12:59 UTC, kristianeboe commented on public/locales/en/collection.json
> +  "estValue": "Est. value",
```suggestion
  "estimatedValue": "Est. value",
```

2022-08-21 17:39 UTC, kespinola requested changes

2022-08-22 07:54 UTC, alchemistgo87 commented on src/pages/profiles/[address]/collected.tsx
> +                    />
Sure!

2022-08-23 20:53 UTC, kespinola approved these changes

2022-08-24 05:21 UTC, merged