Port activity page
holaplex/dao-marketplace pull request #8
Opened 2022-08-16 12:25 UTC by alchemistgo87

Addresses: https://github.com/holaplex/holaplex/issues/686

2022-08-16 16:11 UTC, austinmilt requested changes

2022-08-16 16:11 UTC, austinmilt commented on src/pages/collections/[address]/activity.tsx
> +  console.log('activities query', activitiesQuery);
```suggestion
```

2022-08-17 07:42 UTC, kespinola commented on src/pages/collections/[address]/activity.tsx
> +  ])(activity.activityType);
Going to do this project without ramda. I'll update this with a useMemo and js switch.

2022-08-17 07:42 UTC, kespinola commented on src/pages/collections/[address]/activity.tsx
> +        {format(activity.createdAt, 'en_US')}
It be the same code we try to implement and likely don't case all the edge cases I advocate for timeago.

2022-08-17 07:42 UTC, kespinola commented on src/pages/collections/[address]/activity.tsx
> +  const activitiesQuery = useQuery<CollectionActivitiesData, CollectionActivitiesVariables>(
I want to see the useQuery in the page component for now. Key to refactoring is to repeat the code the same in all places so we can see how the patterns layout. Get clean abstractions after seeing all the use cases laid out instead of abstracting early.

2022-08-17 13:24 UTC, kristianeboe commented on src/pages/collections/[address]/activity.tsx
> +        {format(activity.createdAt, 'en_US')}
In some places we are relying on luxxon, the official replacement for momentjs.

It has a function called .toRelative()
![image](https://user-images.githubusercontent.com/10433154/185144512-e5f8a65a-c702-4959-8f3e-4d996cbb65ef.png)


I think it could pay off to lean into using a library like luxxon, or even more light weight Date-fns and its https://date-fns.org/v2.29.1/docs/formatDistanceToNow

That way we have a fully fledged date library (which might come in handy when we start with the charts etc.) compared to timeago which only does one time.

Timeago does seem to have some kind of "subscribe/unsusbscribe" to increment the "time ago" in real time, but personally I dont't think that outweighs the pros of using luxxon or date-fns

2022-08-17 14:50 UTC, austinmilt commented on src/pages/collections/[address]/activity.tsx
> +  const activitiesQuery = useQuery<CollectionActivitiesData, CollectionActivitiesVariables>(
We already have significant experience with this in both holaplex and marketplace repos.

2022-08-17 15:35 UTC, kespinola commented on package.json
> +    "ramda": "^0.28.0",
removed it.

2022-08-17 15:36 UTC, kespinola commented on src/modules/calculate.ts
> +}
@alchemistgo87 documented and added precision as optional second parameter

2022-08-17 15:38 UTC, kespinola commented on src/pages/collections/[address]/activity.tsx
> +        {format(activity.createdAt, 'en_US')}
going with date-fs making the change.

2022-08-17 15:39 UTC, kespinola commented on src/pages/collections/[address]/activity.tsx
> +  ])(activity.activityType);
done.

2022-08-17 15:41 UTC, kespinola commented on src/pages/collections/[address]/activity.tsx
> +  const activitiesQuery = useQuery<CollectionActivitiesData, CollectionActivitiesVariables>(
neither have nailed it yet. Please bear with me.

2022-08-17 15:41 UTC, kespinola commented on src/pages/collections/[address]/activity.tsx
> +  console.log('activities query', activitiesQuery);
removed.

2022-08-17 16:02 UTC, kespinola commented on src/pages/collections/[address]/activity.tsx
> +        {format(activity.createdAt, 'en_US')}
done.

2022-08-17 16:03 UTC, kespinola approved these changes

2022-08-17 16:34 UTC, merged